Repository shanqiaosong/Scheduler.Backend, pull requests merged in 2020-12, with the labels that each got.

#1 Feat/account
  app/Http/Controllers/AccountController.php
  app/Http/Kernel.php
  app/Models/Account.php
  app/Providers/AuthServiceProvider.php
  config/database.php
  database/migrations/2020_12_04_170541_create_accounts_table.php
  routes/web.php
Labels: enhancement, good first issue

#10 feat/classTime
  app/Http/Kernel.php
  app/Providers/AppServiceProvider.php
  routes/web.php
Labels: enhancement

#11 Feat/ddl
  app/Http/Controllers/DdlController.php
  app/Models/Ddl.php
  database/migrations/2020_12_17_025734_create_ddls_table.php
  routes/web.php
Labels: enhancement

#9 Feat/classInfo
  app/Http/Controllers/ClassInfoController.php
  app/Models/ClassInfo.php
  app/Providers/AppServiceProvider.php
  database/migrations/2020_12_15_035454_create_class_infos_table.php
  routes/web.php
Labels: enhancement

#16 fix some bugs about updating ddl imformation
  app/Http/Controllers/DdlController.php
  database/migrations/2020_12_17_025734_create_ddls_table.php
Labels: bug

#13 Issue our final edition
  app/Http/Controllers/AccountController.php
  app/Http/Controllers/ClassInfoController.php
  app/Http/Controllers/ClassTimeController.php
  app/Http/Controllers/DdlController.php
  app/Http/Kernel.php
  app/Models/Account.php
  app/Models/ClassInfo.php
  app/Models/ClassTime.php
  app/Models/Ddl.php
  app/Providers/AppServiceProvider.php
  app/Providers/AuthServiceProvider.php
  config/database.php
  database/migrations/2020_12_04_170541_create_accounts_table.php
  database/migrations/2020_12_15_035454_create_class_infos_table.php
  database/migrations/2020_12_16_073348_create_class_times_table.php
  database/migrations/2020_12_17_025734_create_ddls_table.php
  routes/web.php
  tests/Feature/AccountTest.php
  tests/Feature/ClassInfoTest.php
Labels: enhancement
